### What is the difference between Descriptive and Inferential Statistics?

- Descriptive Statistics just describe the data you already have. 
- They summarize facts, like the average score of a class or the number of people who liked a movie, using simple tools like charts and graphs.

###

- Inferential Statistics use a small piece of data (a sample) to make a smart guess or prediction about a much larger group (the population). 
- For example, doctors test a drug on 100 people to see if it will likely work for everyone. 

### Differentiate between Discrete and Continuous Probability Distributions.

### What is the importance of standard deviation and variance in data analysis?/

### Define the following:
- Skewness
- Kurtosis
- Outlier


- A bag contains 5 red balls, 4 blue balls, and 3 green balls. One ball is drawn at random.
- a. What is the probability of getting a red ball?
- b. What is the probability of getting a red or blue ball?
- c. What is the probability of not getting a green ball?


In [1]:
total_balls = 5 + 4 + 3
p_red = 5 / total_balls
p_blue = 4 / total_balls
p_green = 3 / total_balls

In [2]:
print(f"Probability of getting red ball is:{p_red}")

Probability of getting red ball is:0.4166666666666667


In [3]:
print(f'Probability of getting red or blue ball is: {p_blue + p_red}')

Probability of getting red or blue ball is: 0.75


In [4]:
print(f'Probability of getting red or blue ball is: {1 - p_green}')

Probability of getting red or blue ball is: 0.75


- Given two vectors:
- A = [2, 3, 1] and B = [1, 0, 4]
- a. Find the dot product of A and B
- b. Are the vectors orthogonal?

In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("Student Attitude and Behavior.csv")
df

Certification Course  Gender Department  Height(CM)  Weight(KG)  \
0                     No    Male        BCA       100.0        58.0   
1                     No  Female        BCA        90.0        40.0   
2                    Yes    Male        BCA       159.0        78.0   
3                    Yes  Female        BCA       147.0        20.0   
4                     No    Male        BCA       170.0        54.0   
..                   ...     ...        ...         ...         ...   
230                  Yes    Male  B.com ISM       170.0        76.0   
231                  Yes    Male  B.com ISM       172.0        52.0   
232                  Yes  Female        BCA       139.0        33.0   
233                  Yes  Female   Commerce       153.0        58.0   
234                   No  Female  B.com ISM       155.0        39.0   

     10th Mark  12th Mark  college mark        hobbies daily studing time  \
0         79.0       64.0          80.0    Video Games      0 - 30 minute   
1         70.0       80.0          70.0         Cinema     30 - 60 minute   
2         71.0       61.0          55.0         Cinema         1 - 2 Hour   
3         70.0       59.0          58.0  Reading books         1 - 2 Hour   
4         40.0       65.0          30.0    Video Games     30 - 60 minute   
..         ...        ...           ...            ...                ...   
230       72.0       67.0          65.0    Video Games     30 - 60 minute   
231       72.0       70.0          76.0         Cinema         2 - 3 hour   
232       90.0       75.0          70.0         Cinema     30 - 60 minute   
233       85.0       74.0          75.0         Cinema      0 - 30 minute   
234       45.0       45.0          50.0         Sports         3 - 4 hour   

    prefer to study in  salary expectation Do you like your degree?  \
0              Morning               40000                       No   
1              Morning               15000                      Yes   
2              Anytime               13000                      Yes   
3              Anytime             1500000                       No   
4              Morning               50000                      Yes   
..                 ...                 ...                      ...   
230            Morning                7000                      Yes   
231            Anytime               25000                      Yes   
232              Night               20000                      Yes   
233            Anytime               20000                      Yes   
234              Night                  10                       No   

    willingness to pursue a career based on their degree    \
0                                                  50%       
1                                                  75%       
2                                                  50%       
3                                                  50%       
4                                                  25%       
..                                                 ...       
230                                                50%       
231                                                75%       
232                                                50%       
233                                                75%       
234                                                75%       

    social medai & video Travelling Time  Stress Level  Financial Status  \
0          1.30 - 2 hour  30 - 60 minutes           Bad              Bad   
1          1 - 1.30 hour   0 - 30 minutes           Bad              Bad   
2       More than 2 hour  30 - 60 minutes         Awful              Bad   
3          1.30 - 2 hour   0 - 30 minutes           Bad             good   
4          1.30 - 2 hour  30 - 60 minutes          Good             good   
..                   ...              ...           ...              ...   
230     More than 2 hour  30 - 60 minutes           Bad              Bad   
231       30 - 60 Mi

In [7]:
A = [2,3,1]
B = [1,0,4]

In [8]:
dot_product = np.dot(A,B)

In [9]:
print(f"The dot product of two vectores is:{dot_product}")

The dot product of two vectores is:6


- You are given the following marks of 20 students:
- 69,35,26,55,28,99,69,50,31,32,23,28,77,80,75,45,69,61,27,48,97
- a. Find the mean, median, and mode
- b. Calculate standard deviation

In [10]:
import statistics

In [11]:
marks = [69,35,26,55,28,99,69,50,31,32,23,28,77,80,75,45,69,61,27,48,97]

In [12]:
mean = np.mean(marks)

In [13]:
median = np.median(marks)

In [14]:
mode = statistics.mode(marks)

In [15]:
std = np.std(marks)

In [16]:
print(f'Mean : {mean},\t Meadian : {median} \t Mode : {mode} \t Standard Deviation : {std} ')

Mean : 53.523809523809526,	 Meadian : 50.0 	 Mode : 69 	 Standard Deviation : 23.475659223197948 


- Use the “Student Attitude and Behavior” dataset and select the following columns: Height, Weight, 10th Marks, 12th Marks.
- Find Mean, Median, Mode and Quartiles
- Find Skewness, kurtosis and Interpretation Based on the Skewness, kurtosis.

In [17]:
new_df = df[['Height(CM)', 'Weight(KG)', '10th Mark' , '12th Mark']]
new_df

Height(CM)  Weight(KG)  10th Mark  12th Mark
0         100.0        58.0       79.0       64.0
1          90.0        40.0       70.0       80.0
2         159.0        78.0       71.0       61.0
3         147.0        20.0       70.0       59.0
4         170.0        54.0       40.0       65.0
..          ...         ...        ...        ...
230       170.0        76.0       72.0       67.0
231       172.0        52.0       72.0       70.0
232       139.0        33.0       90.0       75.0
233       153.0        58.0       85.0       74.0
234       155.0        39.0       45.0       45.0

[235 rows x 4 columns]

In [18]:
new_df.describe()

Height(CM)  Weight(KG)   10th Mark   12th Mark
count  235.000000  235.000000  235.000000  235.000000
mean   157.402128   60.803830   76.848511   68.775872
std     21.510805   14.895844   13.047560   11.018192
min      4.500000   20.000000    7.400000   45.000000
25%    152.000000   50.000000   70.000000   60.000000
50%    160.000000   60.000000   80.000000   69.000000
75%    170.000000   70.000000   86.250000   76.000000
max    192.000000  106.000000   98.000000   94.000000

In [19]:
np.corrcoef(new_df)

array([[1.        , 0.74204252, 0.85796044, ..., 0.96266588, 0.96764466,
        0.89767796],
       [0.74204252, 1.        , 0.49671955, ..., 0.89579729, 0.75991482,
        0.65495437],
       [0.85796044, 0.49671955, 1.        , ..., 0.76988474, 0.93190904,
        0.98034123],
       ...,
       [0.96266588, 0.89579729, 0.76988474, ..., 1.        , 0.94866838,
        0.86008596],
       [0.96764466, 0.75991482, 0.93190904, ..., 0.94866838, 1.        ,
        0.97523781],
       [0.89767796, 0.65495437, 0.98034123, ..., 0.86008596, 0.97523781,
        1.        ]], shape=(235, 235))

- An investment analyst wants to assess the relationship between the stock prices of two 
companies to identify potential investment opportunities. Data: Let's consider the daily closing prices (in dollars) of Company A and Company B for a sample of 20 trading days: 
Company A: 45, 47, 48, 50, 52, 53, 55, 56, 58, 60, 62, 64, 65, 67, 69, 70, 72, 74, 76, 77 Company B: 52, 54, 55, 57, 59, 60, 61, 62, 64, 66, 67, 69, 71, 73, 74, 76, 78, 80, 82, 83
- Calculate the covariance and correlation between the stock prices of Company A and Company B. Interpret the value of the covariance and explain the nature of the relationship between the two stocks.


In [21]:
company_a = [45, 47, 48, 50, 52, 53, 55, 56, 58, 60, 62, 64, 65, 67, 69, 70, 72, 74, 76, 77]
company_b = [52, 54, 55, 57, 59, 60, 61, 62, 64, 66, 67, 69, 71, 73, 74, 76, 78, 80, 82, 83]

covariance_matrix = np.cov(company_a, company_b)
covariance = covariance_matrix[0, 1]

correlation = np.corrcoef(company_a, company_b)[0, 1]

print("Covariance:", covariance)
print("Correlation:", correlation)

Covariance: 97.52631578947368
Correlation: 0.9985957269963789


##### Company A and Company B show a very strong positive linear relationship, meaning their prices tend to rise and fall together.

In [24]:
covariance_matrix = np.cov(company_a, company_b)
covariance_matrix

array([[101.89473684,  97.52631579],
       [ 97.52631579,  93.60789474]])

In [25]:
np.corrcoef(company_a,company_b)

array([[1.        , 0.99859573],
       [0.99859573, 1.        ]])

- A survey was conducted to determine if ice cream flavor preference is related to gender. The following data was collected:



                Chocolate           Vanilla             Strawberry

        Male       20                15                   10   

        Female     25                20                   30

In [26]:
from scipy.stats import chi2_contingency

observed = [[20, 15, 10],
            [25, 20, 30]]

chi2, p_value, dof, expected = chi2_contingency(observed)

print("Chi-square statistic:", chi2)
print("Degrees of freedom:", dof)
print("P-value:", p_value)
print("Expected frequencies:\n", expected)


Chi-square statistic: 4.021164021164021
Degrees of freedom: 2
P-value: 0.13391071453129127
Expected frequencies:
 [[16.875 13.125 15.   ]
 [28.125 21.875 25.   ]]


- In a standardized test, the scores are normally distributed with a mean of 100 and a standard deviation of 15.
- What is the probability that a randomly selected student scores above 115?
- What percentage of students scored between 85 and 115?

In [6]:
from scipy.stats import norm
mean = 100
std_dev = 15

# 1. Probability that score is above 115
prob_above_115 = 1 - norm.cdf(115, mean, std_dev)

# 2. Probability that score is between 85 and 115
prob_between = norm.cdf(115, mean, std_dev) - norm.cdf(85, mean, std_dev)

print("Probability score > 115:", prob_above_115)
print("Percentage between 85 and 115:", prob_between * 100)

Probability score > 115: 0.15865525393145707
Percentage between 85 and 115: 68.26894921370858
